version: "3"
services:
  backend:
    restart: always
    container_name: "backend"
    working_dir: "/opt/backend/app"
    ports:
      - "8080:8000"
  frontend:
    restart: always
    container_name: "frontend"
    working_dir: "/opt/frontend/app"
    ports:
      - "3000:5173"
